// This file is auto-generated by TanStack Router

import { FileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexComponentImport = new FileRoute('/').createRoute()
const ProductIndexComponentImport = new FileRoute('/product/').createRoute()
const OrderIndexComponentImport = new FileRoute('/order/').createRoute()
const OrderIdIndexComponentImport = new FileRoute('/order/$id/').createRoute()

// Create/Update Routes

const IndexComponentRoute = IndexComponentImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.component'),
    'component',
  ),
})

const ProductIndexComponentRoute = ProductIndexComponentImport.update({
  path: '/product/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/product/index.component'),
    'component',
  ),
})

const OrderIndexComponentRoute = OrderIndexComponentImport.update({
  path: '/order/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/order/index.component'),
    'component',
  ),
})

const OrderIdIndexComponentRoute = OrderIdIndexComponentImport.update({
  path: '/order/$id/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/order/$id/index.component'),
    'component',
  ),
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexComponentImport
      parentRoute: typeof rootRoute
    }
    '/order/': {
      preLoaderRoute: typeof OrderIndexComponentImport
      parentRoute: typeof rootRoute
    }
    '/product/': {
      preLoaderRoute: typeof ProductIndexComponentImport
      parentRoute: typeof rootRoute
    }
    '/order/$id/': {
      preLoaderRoute: typeof OrderIdIndexComponentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexComponentRoute,
  OrderIndexComponentRoute,
  ProductIndexComponentRoute,
  OrderIdIndexComponentRoute,
])
